[libraries]
commons-text = "org.apache.commons:commons-text:1.9"
interop-aidbox = "com.projectronin.interop.publish:interop-aidbox:6.1.1"
interop-common-http = "com.projectronin.interop:interop-common-http:3.2.1"
interop-common-jackson = "com.projectronin.interop:interop-common-jackson:3.2.1"
interop-ehr-api = "com.projectronin.interop.ehr:interop-ehr:7.0.1-SNAPSHOT"
interop-ehr-epic = "com.projectronin.interop.ehr:interop-ehr-epic:7.0.1-SNAPSHOT"
interop-ehr-tenant = "com.projectronin.interop.ehr:interop-tenant:7.0.1-SNAPSHOT"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:5.0.1-SNAPSHOT"
interop-validation-client = "com.projectronin.interop.validation:interop-validation-client:1.1.0"
mockk = "io.mockk:mockk:1.13.3"
