[libraries]
commons-text = "org.apache.commons:commons-text:1.9"
interop-aidbox = "com.projectronin.interop.publish:interop-aidbox:7.4.1"
interop-common-http = "com.projectronin.interop:interop-common-http:3.4.0"
interop-common-jackson = "com.projectronin.interop:interop-common-jackson:3.4.0"
interop-ehr-api = "com.projectronin.interop.ehr:interop-ehr:9.3.1"
interop-ehr-epic = "com.projectronin.interop.ehr:interop-ehr-epic:9.3.1"
interop-ehr-tenant = "com.projectronin.interop.ehr:interop-tenant:9.3.1"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:7.5.0"
interop-validation-client = "com.projectronin.interop.validation:interop-validation-client:1.1.0"
mockk = "io.mockk:mockk:1.13.3"
