name: Create Tag
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to tag'
        type: string
        required: true
        default: 'main'

env:
  ronin.release: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute build
        run: ./gradlew build

      - name: Axion Release
        id: release
        run: |
          ./gradlew release -Prelease.customUsername=${{ github.actor }} -Prelease.customPassword=${{ github.token }}
