name: Create Dated Release
on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Determine last tag
        id: last-tag
        run: |
          LAST_TAG=$(git tag --sort=-version:refname | head -n 1)
          echo "::set-output name=tag::$LAST_TAG"

      - name: Determine new tag
        id: tag-name
        run: echo "::set-output name=tag::$(date +'%Y%m%d')"

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          last-tag: ${{ steps.last-tag.outputs.tag }}
          tag: ${{ steps.tag-name.outputs.tag }}
    outputs:
      tag: ${{ steps.tag-name.outputs.tag }}
  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "refs/tags/${{ needs.tag.outputs.tag }}"

      - name: Generate Changelog
        id: changelog
        uses: gandarez/changelog-action@v1.2.0
        with:
          current_tag: ${{ needs.tag.outputs.tag }}
          previous_tag: ${{ needs.tag.outputs.last-tag }}

      - name: Echo changelog
        run: echo ${{ steps.changelog.outputs.changelog }}
