name: Mark Next Release
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Type of version increment to perform for next release'
        type: choice
        required: true
        options:
          - Patch
          - Minor
          - Major

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Mark version
        run: |
          ./gradlew markNextVersion \
             -Prelease.versionIncrementer=increment${{ github.event.inputs.increment }} \
             -Prelease.customUsername=${{ github.actor }} \
             -Prelease.customPassword=${{ github.token }}
