name: Upgrade Dependencies
on:
  workflow_dispatch:
    inputs:
      maxPRs:
        description: 'The maximum number of PRs to create during execution'
        required: true
        default: '5'

jobs:
  tag:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Releases Hub
        run: ./gradlew upgradeDependencies
        env:
          gitHubRepository: ${{ github.REPOSITORY }}
          gitHubWriteToken: ${{ secrets.GITHUB_TOKEN }}
          gitUserEmail: "41898282+github-actions[bot]@users.noreply.github.com"
          gitUserName: "github-actions[bot]"
          pullRequestsMax: ${{ github.event.inputs.maxPRs || '5' }}
          baseBranch: main
